### ISSUE TITLE
設定されたShift_JIS遅延判定文字列バッファサイズを超過しました

### ISSUE THREAD

**Issue by alliance1005** [fw3/streams#31]
少し長め（大きめのSjis）CSVを読込んだ際にエラーが発生致します。
フィルター設定の際に、SJIS_CHECK_DEFERRED_BUFFER_SIZE_DEFAULTの値を変更する方法などはありますか？
Symfony4.4 (PHP 7.4.8) Win10

-----Filter設定
$spec   = StreamFilterSpec::resource($path_to_csv)->read([
    StreamFilterConvertEncodingSpec::toUtf8()->fromSjisWin(),
]);

-----エラー内容
\vendor\fw3\streams\src\filters\ConvertEncodingFilter.php (line 697)
設定されたShift_JIS遅延判定文字列バッファサイズを超過しました。32721 / 24576

-----CSVの情報
ファイル名  C:\Users\Desktop\*******2022-11-14T091806.831.csv
文字コード  SJIS
行数  92行
ファイルサイズ  53882 バイト

**Comment by wakabadou** [comment]
次のサンプルコードで示す通り、`ConvertEncodingFilter::sjisSeparationPositionBufferSize`メソッドを利用して期待するバッファサイズを注入してください。

```php
// 後でバッファサイズを戻すために現状のバッファサイズをキャッシュする
$before_sjis_check_deferred_buffer_size = ConvertEncodingFilter::sjisSeparationPositionBufferSize();

// 静的プロパティとしてバッファサイズを変更する
ConvertEncodingFilter::sjisSeparationPositionBufferSize($sjis_check_deferred_buffer_size);

// -----Filter設定
$spec = StreamFilterSpec::resource($path_to_csv)->read([
    StreamFilterConvertEncodingSpec::toUtf8()->fromSjisWin(),
]);
```
```php
// ～～中略～～
```
```php
// 元の設定に戻す
ConvertEncodingFilter::sjisSeparationPositionBufferSize($before_sjis_check_deferred_buffer_size);
```

Interfaceの都合上、静的プロパティでの対応となります。
実用上、設定しっぱなしでも特に問題はないはずですが、使用後は元の値に戻しておいた方が後々のトラブルは少なくなると考えます。

**Comment by alliance1005** [comment]
解決しました！ありがとうございました。
